### ISSUE TITLE
Locatable::new should take Into<Error>

### ISSUE THREAD

**Issue by jyn514** [jyn514/rcc#181]
I have lots of code that looks like this:

```rust
Locatable::new(
    SemanticError::Generic("invalid preprocessing directive").into(),
    id.location,
),
```

It would be nice to write just `    SemanticError::Generic("invalid preprocessing directive")` instead.

**Comment by pythondude325** [comment]
I noticed that when creating a `CompileError` i would indirectly use the `Locatable::new` function. I thought it would be good to create a `CompileError::new` function for clarity, but it wasn't completely necessary. A `CompileError::new` function would work well to fix this ergonomic issue. A function with the following signature would do nicely:
```rust
fn new(error: impl Into<Error>, location: Location) -> CompileError
```

**Comment by jyn514** [comment]
@pythondude325 you can still write this as an associated function on CompileError, you don't need it to be free: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d0c8f94379a9da93a6db5cf32a320124

**Comment by jyn514** [comment]
You can also _use_ the function as `CompileError::new(...args...)` without a problem.

**Comment by pythondude325** [comment]
I meant it to be inside of an impl block, also this would require no changes to existing usage.
