### ISSUE TITLE
[ICE] Memory allocation error when declaring a large array

### ISSUE THREAD

**Issue by pythondude325** [jyn514/rcc#235]
**Expected behavior**
rcc should give an error when an array is to large.

**Actual Behavior**
```
memory allocation of 274877906940 bytes failed[1]    20342 abort (core dumped)  cargo run
```

**Code**
```c
int i[0xfffffffff];
```

<details><summary>Backtrace</summary>

```
memory allocation of 17179869180 bytes failed[1]    20495 abort (core dumped)  RUST_BACKTRACE=1 cargo run
```
</details>

**Comment by pythondude325** [comment]
I should note that clang will compile this and the binary it produces will cause a segfault at runtime

**Comment by jyn514** [comment]
So, it would be nice to be able to check but I don't think it's possible in Rust. However, we can get around the common case if Cranelift uses `.bss` to store all zeros. This is https://github.com/bytecodealliance/cranelift/pull/1209
