### ISSUE TITLE
Document that compiler targets C99 and C11

### ISSUE THREAD

**Issue by Jnchi** [jyn514/rcc#3]

**Comment by jyn514** [comment]
The goal is to target C99 and C11. If large parts of `glibc` use C89 I might consider adding it, since I want to compile the standard library.

Leaving this issue open until I document it.

**Comment by jyn514** [comment]
Closed in https://github.com/jyn514/rcc/commit/3d34c686ecd236a55f45000c415d16073161debf, see the [FAQ](FAQ.md).
