### ISSUE TITLE
Rename `Analyzer::parse_expr`, etc. to `expr`

### ISSUE THREAD

**Issue by jyn514** [jyn514/rcc#421]
These functions aren't actually related to parsing.

**Comment by hdamron17** [comment]
Should related functions be changed as well? For example:
* [FunctionAnalyzer::parse_expr](https://github.com/jyn514/rcc/blob/master/src/analyze/stmt.rs#L7)
* [parse_expr_with_scope](https://github.com/jyn514/rcc/blob/master/src/analyze/expr.rs#L1347)
